name: puzzle_15_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.5
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed_annotation: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/15puzzle.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
